# Generated by Django 5.0.3 on 2024-06-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='g_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
