# Generated by Django 5.0.3 on 2024-06-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0002_alter_games_g_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='g_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
