# Generated by Django 5.0.3 on 2024-06-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0004_alter_games_options_alter_games_g_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='f_longest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fight',
            name='f_multiplier',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
    ]
