# Generated by Django 5.0.3 on 2024-06-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0005_fight_f_longest_fight_f_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='f_status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('DONE', 'DONE'), ('LAST CALL', 'LAST CALL')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fight',
            name='f_winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
