# Generated by Django 5.0.3 on 2024-06-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0006_alter_fight_f_status_alter_fight_f_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='referral_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
