# Generated by Django 5.0.3 on 2024-06-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0009_alter_userwallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='relpass',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
