# Generated by Django 5.0.3 on 2024-06-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0010_useraccount_relpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='f_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
