# Generated by Django 5.0.3 on 2024-06-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0012_alter_bet_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='amount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fight',
            name='f_status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('CLOSING', 'CLOSING'), ('DONE', 'DONE'), ('LAST CALL', 'LAST CALL')], max_length=50, null=True),
        ),
    ]
