# Generated by Django 5.0.3 on 2024-06-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0013_alter_bet_amount_alter_fight_f_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='f_status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('CLOSING', 'CLOSING'), ('DONE', 'DONE'), ('LAST CALL', 'LAST CALL'), ('DECLARED', 'DECLARED')], max_length=50, null=True),
        ),
    ]
