# Generated by Django 5.0.3 on 2024-08-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0016_bet_fightno_bet_longest_bet_winstat_bet_winning_amnt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
