# Generated by Django 5.0.3 on 2024-08-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0017_alter_bet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='f_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
