# Generated by Django 5.0.3 on 2024-08-15 04:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0018_alter_fight_f_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='f_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
