# Generated by Django 5.0.3 on 2024-08-15 09:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0025_userwallet_w_betlong_userwallet_w_betwins'),
    ]

    operations = [
        migrations.AddField(
            model_name='longestfight',
            name='l_game',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='l_game', to='ugs_app.games'),
        ),
    ]
