# Generated by Django 5.0.3 on 2024-08-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0026_longestfight_l_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longestfight',
            name='l_game',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
