# Generated by Django 5.0.3 on 2024-08-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0027_alter_longestfight_l_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='longestfight',
            old_name='l_game',
            new_name='l_games',
        ),
    ]
