# Generated by Django 5.0.3 on 2024-08-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0028_rename_l_game_longestfight_l_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longestfight',
            name='l_games',
        ),
    ]
