# Generated by Django 5.0.3 on 2024-08-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0029_remove_longestfight_l_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='longestfight',
            name='l_gmid',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
