# Generated by Django 5.0.3 on 2024-08-15 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0030_longestfight_l_gmid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longestfight',
            name='l_gmid',
        ),
    ]
