# Generated by Django 5.0.3 on 2024-08-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0031_remove_longestfight_l_gmid'),
    ]

    operations = [
        migrations.AddField(
            model_name='longestfight',
            name='l_dateclaimed',
            field=models.CharField(default='', max_length=100),
        ),
    ]
