# Generated by Django 5.0.3 on 2024-08-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0033_remove_longestfight_l_dateclaimed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='w_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('BANNED', 'BANNED')], default='ACTIVE', max_length=50),
        ),
    ]
