# Generated by Django 5.0.3 on 2024-08-24 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0034_alter_userwallet_w_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stakefund',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_code', models.CharField(blank=True, max_length=50, null=True)),
                ('s_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('s_date', models.DateTimeField(auto_now=True)),
                ('s_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakefund_sender', to=settings.AUTH_USER_MODEL)),
                ('s_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakefund_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
