# Generated by Django 5.0.3 on 2024-08-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0035_stakefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='w_stakebal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='w_stakecom',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='w_stakeuot',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
