# Generated by Django 5.0.3 on 2024-08-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0036_userwallet_w_stakebal_userwallet_w_stakecom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='wallet_out',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='uwalletcashout',
            name='cw_agent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='default_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
