# Generated by Django 5.0.3 on 2024-08-27 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0037_userwallet_wallet_out_uwalletcashout_cw_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uwalletcashout',
            name='cw_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cw_agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
