# Generated by Django 5.0.3 on 2024-09-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0040_alter_uwalletcashout_cw_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='cOut_approved',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='uwalletcashout',
            name='cw_appdate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uwalletcashout',
            name='cw_approved',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uwalletcashout',
            name='cw_stat',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
