# Generated by Django 5.0.3 on 2024-09-04 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0041_userwallet_cout_approved_uwalletcashout_cw_appdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwallet',
            old_name='cOut_approved',
            new_name='agent_cOut',
        ),
    ]
