# Generated by Django 5.0.3 on 2024-09-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0042_rename_cout_approved_userwallet_agent_cout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uwalletcashout',
            old_name='cw_agent',
            new_name='cw_agentid',
        ),
    ]
