# Generated by Django 5.0.3 on 2024-08-18 03:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StakeLogs',
            fields=[
                ('sl_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sl_name', models.CharField(blank=True, default=0, max_length=50)),
                ('sl_rate', models.IntegerField(blank=True, default=0)),
                ('sl_amount', models.IntegerField(blank=True, default=0)),
                ('sl_type', models.CharField(blank=True, default=0, max_length=50)),
                ('sl_status', models.CharField(choices=[('PENDING', 'PENDING'), ('RECIEVED', 'RECIEVED'), ('SEND', 'SEND')], default='PENDING', max_length=50)),
                ('sl_duration', models.IntegerField(blank=True, default=0)),
                ('sl_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
